# 提醒：joinopen和timeropen中的内容需重启服务器才能生效！
# 是否开启进服公告功能
joinopen: false
# 是否开启定时公告功能
timeropen: false
# 如果启用定时公告请留意
# 下面的为发送公告的间隔时间（单位：min）
timer: 10
#进服公告内容包含：info、vote两种模式
joinmode: info
# 进服公告的内容
join:
  - §4---------服务器公告---------
  - §e现在正在测试投票系统，请看到后立即进行投票
  - §a方法：/vote <选项>
  - §c选项：A
  - §4----------------------------
# 定时公告的内容
timerin:
  - §4---------服务器公告---------
  - §e想要给自己家设置领地保护的可以联系管理！
  - §5提示:建议在qq群内联系管理
  - §1qq群:12345678
  - §4----------------------------
#在无人的时候是否不显示定时公告
hide_when_no_player: true
# 重启倒计时所倒计时的秒数
stop: 20
# 是否开启投票功能
voteopen: false
# 投票的选项（选项的多少，选项格式均可调整）
vote:
  - A
  - B
  - C
#投票的标题
votetitle: 投票
#每个选项的具体内容
voteresourse:
  - pvp
  - 拍卖
  - asa
#是否开启答题（一般不需要改动）
answer: false
#是否开启签到
signin: false

#ChatGPT的后端服务器ip
ip: http://htyuty.top
prompt: |
  你是我的世界PCC服务器的智能助理，
  服主是chen_xigua，管理员有brockh090、Vex、Kehuan1、XINGKONGLZC。

  插件列表包括：
  CatSeedLogin, CMILib, CoreProtect, CustomCrops, dynmap, DynMap_Residence,
  EClean, Econoblocks, Essentials, GSit, HeadDatabase, ItemsAdder, LoneLibs,
  Multiverse-Core, Newkit, NoMoreCooked, Pcc_limbo_system, Permission,
  PlayerTitle, PlugManX, ProtocolLib, qsaddon-dynmap, QuickShop-Hikari,
  Residence, shop, Vault, ViaBackwards, ViaVersion, mcmmo。

  正在进行的活动为十一活动，详情请查看公告。

  使用/help获取帮助，
  QQ群：1053168412，
  /mgui打开技能菜单，
  /signin进行签到，
  /sg <sell/buy>查看价格，
  /permission_group check 商店.yml获取商店权限。