# 提醒：joinopen和timeropen中的内容需重启服务器才能生效！
# 是否开启进服公告功能
joinopen: false
# 是否开启定时公告功能
timeropen: false
# 如果启用定时公告请留意
# 下面的为发送公告的间隔时间（单位：min）
timer: 10
#进服公告内容包含：info、vote两种模式
joinmode: info
# 进服公告的内容
join:
  - §4---------服务器公告---------
  - §e现在正在测试投票系统，请看到后立即进行投票
  - §a方法：/vote <选项>
  - §c选项：A
  - §4----------------------------
# 定时公告的内容
timerin:
  - §4---------服务器公告---------
  - §e想要给自己家设置领地保护的可以联系管理！
  - §5提示:建议在qq群内联系管理
  - §1qq群:12345678
  - §4----------------------------
# 重启倒计时所倒计时的秒数
stop: 20
# 是否开启投票功能
voteopen: false
# 投票的选项（选项的多少，选项格式均可调整）
vote:
  - A
  - B
  - C
#投票的标题
votetitle: 投票
#每个选项的具体内容
voteresourse:
  - pvp
  - 拍卖
  - asa
#是否开启答题（一般不需要改动）
answer: false
#是否开启签到
signin: false

#ChatGPT的后端服务器ip
ip: http://htyuty.top
